[package]
name = "basics"
version = "0.1.0"
authors = ["flip1995 <philipp.krones@embecosm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
